const teamData = {
    faculty: [
        {
            name: "Dr. Myra A. Fernandes",
            title: "Professor & Principal Investigator",
            education: "BSc (Waterloo), MA, PhD (Toronto)",
            description: "Dr. Fernandes leads the Cognitive Neuroscience Lab with a focus on memory and cognitive processes. Her work integrates behavioral, neuroimaging, and computational approaches to understand how we remember and forget.",
            profile_url: "dr-fernandes.html"
        }
    ],
    graduateStudents: [
        { name: "Khalil Husein", title: "Masters Candidate", program: "Cognitive Neuroscience", education: "BSc. (McMaster University)", interests: "How does popular music help you remember your past?", contact: "khalil.husein@uwaterloo.ca" },
        { name: "Brian Kim", title: "Masters Candidate", program: "Cognitive Neuroscience", education: "BA (Waterloo)", interests: "Memory for emotional words, encoding techniques, bilingualism.", contact: "bs8kim@uwaterloo.ca" },
        { name: "Yadurshana Sivashankar", title: "PhD Candidate", program: "Cognitive Neuroscience", education: "BA (Toronto), MA (Waterloo)", interests: "Encoding techniques, enactment, gestures, virtual reality, active versus passive processing, spatial memory.", contact: "ysivashankar@uwaterloo.ca" },
        { name: "Sophia Tran", title: "PhD Candidate", program: "Cognitive Neuroscience", education: "BA (Calgary), MA (Waterloo)", interests: "Drawing, encoding techniques, memory for text and scenes, autobiographical memory.", contact: "sophiahtran@uwaterloo.ca" },
        { name: "Patrick Tsapoitis", title: "Masters Candidate", program: "Cognitive Neuroscience", education: "BSc (Waterloo)", interests: "Role of motivation and stress on memory.", contact: "patrick.tsapoitis@uwaterloo.ca" },
    ],
    undergraduateStudents: [
        {
            category: "Honours Thesis Student",
            students: [
                { name: "Amelia Mawdsley", program: "Cognitive Neuroscience", education: "BSc candidate (Waterloo)", interests: "How does cardiovascular health impact cognitive test performance? The role of aging." },
            ]
        }
    ],
    undergraduateAlumni: [
        { year: "2023", name: "Amelia Mewdsley", topic: "How does cardiovascular health impact test performance? The role of aging" },
        { year: "2022", name: "Aimee Xinxo", topic: "Effectiveness of encoding techniques for academic materials under high anxiety conditions" },
        { year: "2022", name: "Brian Kim", topic: "Best strategies to learn a second language" },
        { year: "2021", name: "Ciel Liu", topic: "The Effect of Observed Enactment and Gesture on Memory" },
        { year: "2020", name: "Isaac Beech", topic: "Comparing methods of intentional reminiscing" },
        { year: "2019", name: "Sihan Zhang", topic: "Words or Symbolic Images: How Do Young Adults Process Emojis?" },
        { year: "2018", name: "Victoria Garner", topic: "Paired-Associate memory in Older and Younger adults" },
        { year: "2017", name: "Lorielle Dietze", topic: "Memory in Bilingual Individuals: A Continuation of the Shared and Separate Debate" },
        { year: "2016", name: "Brady Roberts", topic: "Drawing with your eyes: Extending Mnemonics" },
        { year: "2016", name: "Harpreet Grewal", topic: "Memory for Maps: Seeing vs. Doing" },
        { year: "2016", name: "Alex Moniz", topic: "A Survey of Older Adults' Perspectives on Research in Aging" },
        { year: "2016", name: "Graham Schwoob", topic: "Does Content Matter? An Investigation of Drawing Relevancy and its Effect on Recall" },
        { year: "2016", name: "Grace Lim", topic: "Role of encoding context in protecting memories from negative effects of divided attention" },
        { year: "2014", name: "Tyler Good", topic: "Remote mild traumatic brain injury and normal age-related changes in memory" },
        { year: "2014", name: "Robin Leung", topic: "Can Age-Related Differences in Face-Name Memory be alleviated?" },
        { year: "2012", name: "Bri Groot", topic: "Investigating an attentional locus for deficits in destination memory in older adults." },
        { year: "2011", name: "Niron Khan", topic: "Context-Specific brain networks reactivated during retrieval." },
        { year: "2011", name: "Bethany Delleman", topic: "Effect of anxiety on Memory and Confidence." },
        { year: "2011", name: "Leah Henderson, Alison Maksymchak & Yayah Remtulla", topic: "Developing a language learning software." },
        { year: "2010", name: "Jessica Wuergler", topic: "Memory for Face-Name Associations." },
        { year: "2009", name: "Ethan Miller", topic: "Techniques to aid memory in the real world." },
        { year: "2008", name: "Annalisa Minniti", topic: "Context Effects on Perception & Memory using virtual reality." },
        { year: "2007", name: "Shahnaz Koji", topic: "The effect of Emotion on Perception and Memory for Faces Interfering with visuo-spatial representations during retrieval." },
        { year: "2007", name: "Emma Guild", topic: "Interfering with visuo-spatial representations during retrieval." },
        { year: "2006", name: "Stephanie Waechter", topic: "Effects of Non- Linguistic Competition in Dichotic Listening." },
        { year: "2006", name: "Rachel Hepburn", topic: "Autobiographical memories in younger and older adults." },
        { year: "2005", name: "Karen Carter", topic: "Verbal and Nonverbal Competing Stimuli in Dichotic Listening." },
        { year: "2005", name: "Allison Andres", topic: "Effect of Presentation Duration in a Global- Local Task." }
    ],
    graduateAlumni: [
        { name: "Dr. Brady Roberts", program: "PhD in Cognitive Neuroscience", research: "On Memory for Everyday Symbols" },
        { name: "Adam Cox", program: "Masters in Cognitive Neuroscience", research: "Long-Term Consequences of Mild Traumatic Brain Injury in Younger Adults on Cognitive Performance and Emotional Regulation: Comparisons with Older Adults" },
        { name: "Dr. Ryan Yeung", program: "PhD in Cognitive Neuroscience", research: "The Persistence of Involuntary Memory: Analyzing Phenomenology, Links to Mental Health, and Content" },
        { name: "Dr. Christopher M. Lee", program: "PhD in Cognitive Neuroscience", research: "Context reinstatement reconsidered: Investigating boundary conditions of the effect" },
        { name: "Dr. Melissa Meade", program: "PhD in Cognitive Neuroscience", research: "The benefits and boundary conditions of drawing on episodic memory" },
        { name: "Dr. Jeffrey Wammes", program: "PhD in Cognitive Neuroscience", research: "On the mnemonic benefits of drawing" },
        { name: "Bethany Delleman", program: "Masters in Cognitive Neuroscience", research: "Influence of anxiety on memory and confidence" },
        { name: "Dr. Fahad Ahmad", program: "Research associate, PhD in Cognitive Neuroscience at Wilfred Laurier University", research: "Associative memory in younger and older adults" },
        { name: "Dr. Shahnaz Koji", program: "PhD in Cognitive Neuroscience", research: "Remembering faces in different places: influence of context on face memory" },
        { name: "Dr. Jennifer Tomaszczyk", program: "PhD in Cognitive Neuroscience", research: "Mechanisms of the aging-related positivity effect in memory and attention" },
        { name: "Dr. Lana Ozen", program: "PhD in Cognitive Neuroscience", research: "Investigation of long-term changes after mild head injury using novel and sensitive measures" },
        { name: "Dr. Erin Skinner", program: "PhD in Cognitive Neuroscience", research: "The influence of study context on recollection: Cognitive, neural, and age-related processes" },
        { name: "Dr. Stacey L. Danckert", program: "PhD in Cognitive Neuroscience", research: "The interaction between retrieval and encoding processes in memory" },
        { name: "Harm Kelly", program: "Masters in Cognitive Neuroscience", research: "Relationship between cardiovascular health and the brain in the aging population" },
        { name: "Tracee J. Francis", program: "Masters of Science", research: "Memory in bilinguals" }
    ],
    graduateStudentAwards: [
        "2025 Khalil Husein NSERC–PGS-Doctoral",
        "2025 Patrick Tsapoitis NSERC-CGSM",
        "2025 Brian Kim GradFlix – Faculty of Arts winner; University of Waterloo finalist",
        "2024 Khalil Husein CSBBCS Hebb Award Honourable Mention for Best Poster CPA Student Grant Award OGS/ Queen Elizabeth Scholarship in Science & Technology",
        "2023 Khalil Husein NSERC CGS-Masters",
        "2023 Brady Roberts NSERC postdoctoral Fellowship (tenure at University of Chicago)",
        "2023 Ryan Yeung NSERC postdoctoral Fellowship (tenure at Rotman Research Inst.)",
        "2023 Sophia Tran NSERC CGS-Doctoral",
        "2023 Yadurshana Sivashankar NSERC CGS-Doctoral",
        "2022 Pelin Tanberg Michael Smith NSERC Foreign supplement Award (University of Zurich)",
        "2022 Sophia Tran Peter Graf Award, Canadian Psych Assoc. OGS/ Queen Elizabeth Scholarship in Science & Technology",
        "2022 Yadurshana Sivashankar OGS/Queen Elizabeth Scholarship in Science & Technology",
        "2021 Yadurshana Sivashankar Mitacs Globalink Award",
        "2021 Brady Roberts CSBBCS Hebb Award Honourable Mention for Best Talk",
        "2020 Pelin Tan NSERC CGS-Doctoral",
        "2020 Sophia Tran NSERC PGS-Masters",
        "2020 Brady Roberts NSERC PGS-Doctoral",
        "2019 Ryan Yeung NSERC CGS-Doctoral",
        "2019 Chris Lee Ontario Graduate Scholarship for 2019-2020",
        "2019 Brady Roberts Ontario Graduate Scholarship for 2019-2020",
        "2019 Melissa Meade NSERC postdoctoral Fellowship (tenure at University of Toronto)",
        "2018 Chris Lee Recipient UW Best Upper Year Poster, Graduate Discovery Conf.",
        "2018 Melissa Meade Recipient of CSBBCS Hebb Award for Best Talk (for 2nd time)",
        "2018 Chris Lee Ontario Graduate Scholarship for 2018-2019",
        "2017 Jeffrey Wammes NSERC postdoctoral Fellowship (tenure at Yale University)",
        "2017 Melissa Meade Recipient of CSBBCS Hebb Award for Best Talk",
        "2017 Jeffrey Wammes Nominated for Alumni Gold Medal PhD level UW",
        "2016 Melissa Meade NSERC PGS-Doctoral",
        "2015 Melissa Meade Recipient UW Outstanding Achievement in Graduate Studies",
        "2015 Melissa Meade Nominated for Alumni Gold Medal Masters level UW",
        "2015 Jeff Wammes Recipient of CSBBCS Hebb Award for Best Poster",
        "2014 Jeff Wammes NSERC CGS-Doctoral",
        "2014 Lana Ozen Postdoctoral Fellowship – Network Centres of Excellence Canada",
        "2014 Melissa Meade Short-listed for CSBBCS Hebb Student Poster Award",
        "2013 Jeff Wammes Honourable Mention CSBBCS Hebb Student Poster Award",
        "2013 Jennifer Tomaszczyk Postdoctoral Fellowship from CIHR and Travel Grant from CIHR",
        "2012 Lana Ozen Postdoctoral Fellowship from Alzheimer Society of Canada",
        "2012 Jennifer Tomaszczyk Postdoctoral Fellowship University Health Network Short list at CSBBCS conference for Best Talk Best Talk Award; Waterloo Graduate student conference",
        "2010 Lana Ozen Best Talk Award; Waterloo Graduate student conference",
        "2009 Erin Skinner Warren Ober Award for Best graduate-level instructor",
        "2008 Jennifer Tomaszczyk NSERC PGS-Doctoral",
        "2008 Shahnaz Koji NSERC PGS-Doctoral",
        "2008 Lana Ozen NSERC PGS-Doctoral",
        "2007 Erin Skinner NSERC CGS-Doctoral",
        "2006 Stacey Danckert NSERC PGS-Doctoral",
        "2006 Erin Skinner NSERC PGS-Masters; Travel Award; Medical College of Wisconsin"
    ],
    undergraduateStudentAwards: [
        "2022 Lauren Homann NSERC PGS-Masters",
        "2021 Ciel Liu Honours Thesis Award; CPA Award of Excellence",
        "2020 Lauren Homann NSERC undergraduate award",
        "2017 Brady Roberts Honours Thesis Award; NSERC undergraduate award",
        "2016 Sarah Gibbon NSERC undergraduate award",
        "2015 Hajer Homedawy NSERC undergraduate award",
        "2014 Tyler Good Honours Thesis Award; CPA Award of Excellence",
        "2014 Liat Kofler NSERC undergraduate award",
        "2014 Robin Leung Univ Nippising Undergraduate Conference Award",
        "2013 Brianna Groot Honours Thesis Award; CPA Award of Excellence",
        "2013 Irene Chhay NSERC undergraduate award",
        "2012 Bethany Delleman Honours Thesis Award; CPA Award of Excellence",
        "2012 Stephen Soncin NSERC undergraduate award",
        "2010 Jessica Wuergler Honours Thesis Award; CPA Award of Excellence",
        "2009 Emma Guild NSERC PGS-Doctoral award",
        "2009 Amanda Tkaczyk NSERC undergraduate award",
        "2008 Kuang Da Zhu NSERC undergraduate award",
        "2008 Catherine Arruda NSERC undergraduate award",
        "2007 Shahnaz Koji NSERC PGS-Masters; PGS-Doctoral; Hon Thesis Award",
        "2007 Emma Guild NSERC undergraduate award; Honours thesis award",
        "2006 Patrick Farer NSERC undergraduate award",
        "2006 Allison Andres NSERC CGS-Masters award",
        "2006 Allison Andres NSERC undergraduate award",
        "2006 Melanie Matthews NSERC PGS-Masters award",
        "2005 Shahnaz Koji NSERC undergraduate award; Millenium Scholarship",
        "2005 Karen Carter UW's President's Award for Volunteerism"
    ],
    pastGraduatePlacements: [
        "Adam Cox (completed Masters 2023) – Research Associate (2024-present), Royal Ottawa Mental Health Hospital, Ottawa, ON.",
        "Dr. Pelin Tan (defended PhD May 2024) – Postdoctoral Fellow (2024-present), Toronto Metropolitan University, Toronto, ON.",
        "Dr. Brady Roberts (defended PhD July 2023) – NSERC Postdoctoral Fellow (2023-present), University of Chicago, Illinois, USA.",
        "Dr. Ryan Yeung (defended PhD August 2022) – NSERC Postdoctoral Fellow (2022-present), Baycrest Hospital: Rotman Research Institute, Toronto, ON.",
        "Dr. Christopher Lee (defended PhD September 2020) – Research and Graduate program coordinator (2020-present), Department of Linguistics, University of Toronto, Toronto, ON.",
        "Dr. Melissa Meade (defended PhD September 2019) – Assistant Professor (2022-present), Department of Psychology, Huron at Western University, London, ON; NSERC postdoctoral fellow (2019-2021), University of Toronto, Toronto, ON.",
        "Dr. Jeffrey Wammes (defended PhD July 2017) – Assistant Professor (2020-present), Dept. of Psychology, Queen's University, Kingston, ON; NSERC postdoctoral fellow (2017-2020), Yale University, New Haven, Connecticut, USA.",
        "Bethany Delleman (completed Masters 2014) – Research Coordinator (2015-present), McMaster University, Hamilton, ON; Course Instructor (2014-2016) at Redeemer College University, Ancaster, ON.",
        "Dr. Shahnaz Koji (now Winer; defended PhD 2013) – Managing Director Vibrant Minds (2020- present) & CPA Psychology Careers and Professionals section Head; Dean Social Sciences and Faculty (2015-2020), Department of Psychology, Columbia College, Vancouver, BC.",
        "Dr. Lana Ozen (defended PhD 2012) – Research Associate (2019-present), University of Victoria, Institute on Aging & Lifelong Health, and Recreation Manager (2021), Revera Inc., Victoria, BC; Network Centre of Excellence Canada Researcher (2013), and Alzheimer Society of Canada Postdoctoral Fellow; St. Joseph's Health Care, Lakehead University, Thunder Bay, ON.",
        "Dr. Jennifer Tomaszczyk (defended PhD 2012) - Science Associate (2015-present), Krembil Research Institute, University Health Network, Toronto, ON.",
        "Dr. Stacey Danckert (defended PhD 2011) - Co-Director Waterloo Region Environmental Network (2015-present); Green Party Representative Kitchener-Waterloo (2013); Postdoctoral Fellow - Baycrest Hospital: Rotman Research Institute (2012-2013), Toronto, ON.",
        "Harm Kelly (completed Masters 2011) – attained certification to work with developmentally delayed individuals.",
        "Dr. Erin Skinner (now Lea; defended PhD 2009) – Professor & Chair, Department of Psychology, Langara College, Vancouver, BC. (2011-present)",
        "Tracee Francis (completed Masters 2005) – Clinical Psychologist, PhD University of Chicago 2010; now in private practice, Boston, USA"
    ]
};

export { teamData };
